name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t my-ci-image .

      - name: Run tests inside Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            my-ci-image \
            bash -c "
              poetry run flake8 src/lab_monitor tests && \
              poetry run pylint src/lab_monitor && \
              poetry run pdoc src/lab_monitor --html --output-dir docs && \
              poetry run pytest --cov=lab_monitor --cov-report=term --cov-report=html
            "

      - name: Upload coverage report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_html_report/