name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run flake8 lint
        run: poetry run flake8 src/lab_monitor tests

      - name: Run pylint lint
        run: poetry run pylint src/lab_monitor

      - name: Generate docs with pdoc3
        run: poetry run pdoc src/lab_monitor --html --output-dir docs

      - name: Run tests with coverage
        run: poetry run pytest --cov=lab_monitor --cov-report=term --cov-report=html

      - name: Upload coverage report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_html_report/